[workspace]
resolver = "2"
members = ["crates/*"]
default-members = ["crates/eoka-agent"]

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/cbxss/eoka-tools"
homepage = "https://github.com/cbxss/eoka-tools"
authors = ["cbxss"]
